### ISSUE TITLE
Maybe could build the release binary in visual studio 'Release' mode

### ISSUE THREAD

**Issue by 916980name** [Erruar/RTSS-CLI#1]
I got errors when using the release binary, such like "mfc140ud.dll not found", "vcruntime140d.dll not found".
After read some blogs to know that dll file suffix with 'd' is required by debug mode, like "xxxxd.dll".
I have tried to build in release mode in my machine and worked.

**Comment by Erruar** [comment]
Hello @916980name! I'll **add** those libraries in app releases. **Thanks for your feedback**. _I have those libraries in Visual Studio and I forgot to add them in final project release._ Thanks

**Comment by Erruar** [comment]
Added into releases and readme
